-- =============================================
-- Talently — Migración 015: client_logs (logging remoto del APK)
-- Aplicada en Supabase: 2026-06-05 (versionada retroactivamente el 2026-06-11:
-- el archivo nunca se commiteó — hallazgo 🟡 del QA audit 2026-06-10).
-- Reconstruida desde el schema live (information_schema + pg_policy).
--
-- Tabla de logs remotos que escribe src/lib/errorLogger.js (fetch directo al
-- REST endpoint con la anon key). INSERT abierto a anon/authenticated BY
-- DESIGN: el APK debe poder reportar errores incluso sin sesión (el lint
-- rls_policy_always_true de los advisors está aceptado para esta tabla).
-- Lectura: NO hay policy de SELECT — los logs solo se leen vía service_role
-- (el asistente, por MCP).
-- =============================================

CREATE TABLE IF NOT EXISTS public.client_logs (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  timestamptz DEFAULT now(),
    level       text,
    context     text,
    message     text,
    detail      jsonb,
    platform    text,
    user_agent  text,
    app_url     text,
    user_email  text
);

ALTER TABLE public.client_logs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS client_logs_insert_any ON public.client_logs;
CREATE POLICY client_logs_insert_any ON public.client_logs
    FOR INSERT TO anon, authenticated
    WITH CHECK (true);
